name: Update README Fun Fact

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
  # This runs the workflow every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-fact:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Check out repo
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Run the Python script to update the README
      - name: Update README with new fact
        run: python update_readme.py

      # Step 4: Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "CHORE: Update daily fun fact"
          git push